const CONFIG = {
    introTitle: 'Hí bạn',
    introDesc: `Khảo sát tý thôi mà nhớ là trả lời thật lòng nha =))`,
    btnIntro: 'Ok nè',
    title: 'Bạn có yêu quý Khánh không nè :33',
    desc: 'Chọn đi',
    btnYes: 'Có nèeee hiiii',
    btnNo: 'Không, Bạn bị ảo ak ???',
    question:'Sau 4 năm học bạn thấy Khánh là người ntn nhỉ :333',
    btnReply: 'Gửi nèee <3',
    reply: 'Khánh cũng dễ mến này, đẹp trai, tốt bụng nữa <33333333',
    mess: 'Khánh biết mà. Không ngờ bạn nói thế á. Ngại waa :3',
    messDesc: 'Lúc nào sn Khánh nhớ tặng quá nhéeeee',
    btnAccept: 'Okiiiii lun <3',
}
